---
- name: Set route id
  set_fact:
    route_network: "{{ item.network }}"
    route_id: "{{ item.network | checksum }}"

- name: Set route vars
  set_fact:
    route_state: "{{ item.state | default('present') }}"
    route_if_up_script: "/etc/network/if-up.d/{{ interface.name | regex_replace('\\.', '-') }}-{{ route_id }}"
    route_if_down_script: "/etc/network/if-down.d/{{ interface.name | regex_replace('\\.', '-') }}-{{ route_id }}"

- name: Create route
  include_tasks: create.yml
  when: route_state == 'present'

- name: Delete route
  include_tasks: delete.yml
  when: route_state != 'present'
